// <auto-generated />
using GApiProto.MasterMemoryModel;
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using GApiProto.Tables;

namespace GApiProto
{
   public sealed class DatabaseBuilder : DatabaseBuilderBase
   {
        public DatabaseBuilder() : this(null) { }
        public DatabaseBuilder(MessagePack.IFormatterResolver resolver) : base(resolver) { }

        public DatabaseBuilder Append(System.Collections.Generic.IEnumerable<Person> dataSource)
        {
            AppendCore(dataSource, x => x.PersonId, System.Collections.Generic.Comparer<int>.Default);
            return this;
        }

    }
}