CREATE TABLE `user`.`user_profile` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `crystal` INT UNSIGNED NOT NULL DEFAULT 0,
  `crystal_free` INT UNSIGNED NOT NULL DEFAULT 0,
  `friend_coin` INT UNSIGNED NOT NULL DEFAULT 0,
  `tutorial_progress` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC));
